#!name=Youtube ADS by BlackMagicc
#!desc=Youtube & Youtube Music (IOS >= 15)
#Credit: DrStrangeVN, YanbingJiang

[Rule]
AND,((DOMAIN-SUFFIX,googlevideo.com), (PROTOCOL,UDP)),REJECT
AND,((DOMAIN,youtubei.googleapis.com), (PROTOCOL,UDP)),REJECT

[Script]
youtube.request = type=http-request,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|reel\/reel_watch_sequence),requires-body=1,max-size=-1,binary-body-mode=1,script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/dist/youtube.request.preview.js

[Map Local]
^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&oad - REJECT-IMG

[MITM]
hostname = %APPEND% *.googlevideo.com, youtubei.googleapis.com
